name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APP_NAME: github-actions-ci-cd-app

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate Commit Message
        run: |
          echo "commit_message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Print Commit Message
        run: echo "Last commit message was: $commit_message"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build --if-present

      - name: Run Tests
        run: npm test --if-present

      - name: Echo App Name from ENV
        run: echo "Deploying $APP_NAME"

      - name: Use GitHub Secret (without exposing value)
        run: echo "Secret is configured and available"
        env:
          MY_SECRET_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}

