name: Node.js CI

# When the workflow should run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# What the workflow does
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]  # Test on multiple versions

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build --if-present

      - name: Run Tests
        run: npm test

